using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PayloadSigning {

    /// <summary>
    /// Represents an object that can sign and verify payloads using a secret key.
    /// The payload itself is not encrpted, so it is not secret.
    /// But the signature allows parties to verify that it was generated by the holder of the secret key.
    /// </summary>
    public interface IPayloadSigner {

        /// <summary>
        /// Adds a signature to a byte array and returns the result
        /// </summary>
        byte[] Sign(byte[] payload);

        /// <summary>
        /// Verifies the signature of a payload and outputs the payload without signature.
        /// Returns true if the operation was successful, false otherwise
        /// </summary>
        bool TryVerifySignature(byte[] signedPayload, out byte[] payload);
    }
}
